name: Deploy to Near S3

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x ]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.DODAO_ONBOARDING_SCHEMAS_ACCESS_TOKEN }}
          persist-credentials: true
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn install, build, lint
        run: |
          yarn
          yarn run build
          yarn run lint
        env:
          NODE_OPTIONS: --max-old-space-size=4096
          VITE_DEFAULT_NETWORK: mainnet
          VITE_BLOCKCHAIN: NEAR
          VITE_ENVIRONMENT: prod
          VITE_HUB_URL: https://api.onboarding.dodao.io:443
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks
        env:
          AWS_S3_BUCKET: near.dodao.io
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'   # optional: defaults to us-east-1
          SOURCE_DIR: 'dist'      # optional: defaults to entire repository
          VITE_ENVIRONMENT: prod
